#!/usr/bin/python3
import time, subprocess, sys

def CurrentTime():
    current_time = time.strftime("%H:%M")
    hour, minutes = current_time.split(":")
    return int(hour), int(minutes)

def GetUserTime(user_time:str):
    user_hour, user_minutes = user_time.split(":")
    if  user_minutes == "00":user_minutes = 60
    return int(user_hour), int(user_minutes)

def Remind(min_time:str=None, max_time:str=None):
    try:
        if min_time == None and max_time == None:
            params = sys.argv
            min_time, max_time = params[1], params[2]

        min_user_hour, min_user_minutes = GetUserTime(user_time=min_time)
        max_user_hour, max_user_minutes = GetUserTime(user_time=max_time)

        current_hour, current_minutes = CurrentTime()
    
        text_title, text_body = CreateTexts()

        command = f'notify-send "{text_title}" "{text_body}"'

        if max_user_hour >= current_hour >= min_user_hour:
            if max_user_minutes >= current_minutes:
                print(f"\n {text_title}\n{text_body}")
                run_command(command=command)
    except IndexError:
        print(
                "Необхдимо передать параметры в Remind!\n"
                "Смотри https://github.com/rickert156/HomeScripts"
                )
    except ValueError:
        print(
                "Необходимо правильно передать параметры!\n"
                "Смотри https://github.com/rickert156/HomeScripts"
                )

def CreateTexts():
    title = "Чувак, время заниматься!"
    body = """\

    Почитай новости сначала:
    https://google.com
    https://github.com

    После этого можешь начать заниматься по своей литературе.

    Удачного дня, чудак!
    """
    return title, body

def run_command(command:str):
    subprocess.run(command, shell=True)


Remind()
